language: python

python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pylint
addons:
  apt:
    packages:
      - ninja-build
      - doxygen
script:
  - pylint --disable=R,C --rcfile=.pylintrc source/*.py
  - make
  - make check
