# File automatically generated by configure.py, do not modify

CONFIG = python tools/configure.py -f tools/settings.json $(FLAGS)

default: build

.PHONY: configure targets sublime codeblocks

configure:
	@$(CONFIG) --ninja --makefile

build: configure
	@ninja

clean:
	@ninja -t clean

targets:
	@$(CONFIG) --targets

sublime:
	@$(CONFIG) --sublime

codeblocks:
	@$(CONFIG) --codeblocks

release: configure
	@ninja release

debug: configure
	@ninja debug

doxygen: configure
	@ninja doxygen

all: configure
	@ninja all
